version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "a3:ce:2b:91:ef:fe:b2:3f:20:3b:81:64:5d:62:72:0b"
      - checkout
      - run: echo -e "Host vcs.utwente.nl\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git submodule update --init --recursive

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle :parser:build